# GitHub action workflow
name: test vars

on: workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Display Environment Variables
        run: |
          echo "NPM_AUTH_TOKEN: $NPM_AUTH_TOKEN"
