name: Publish npm Package

on:
  push:
    branches:
      - version-4.0.1  # Set the branch you want to trigger the workflow on

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Prepare package for publishing
        run: npm run publish-prepare

      - name: Set npm token
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > .npmrc

      - name: Publish to npm registry
        run: npm publish
